version: '3'
services:
  dev_database:
    image: postgres
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_DB: dev_carmuk
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: